
#Increase melee damage
[strength]
	#Range: 1 ~ 2
	renderRow = 1
	#Range: 1 ~ 3
	renderColumn = 1

#Increase critical chance
[criticalstrike]
	#Range: 1 ~ 2
	renderRow = 2
	#Range: 1 ~ 3
	renderColumn = 1

#Increase bow charge speed
[quickdraw]
	#Range: 1 ~ 2
	renderRow = 1
	#Range: 1 ~ 3
	renderColumn = 2

#Increase arrow velocity
[arrowspeed]
	#Range: 1 ~ 2
	renderRow = 2
	#Range: 1 ~ 3
	renderColumn = 2

#Decrease damage taken
[ironskin]
	#Range: 1 ~ 2
	renderRow = 1
	#Range: 1 ~ 3
	renderColumn = 3

#Increase speed while sneaking
[sneakspeed]
	#Range: 1 ~ 2
	renderRow = 2
	#Range: 1 ~ 3
	renderColumn = 3

#Every X ticks, chance to grow crops around
[greenthumb]
	#Range: 1 ~ 2
	renderRow = 1
	#Range: 1 ~ 3
	renderColumn = 1

#Chance to gather extra crops on harvest
[harvestproficiency]
	#Range: 1 ~ 2
	renderRow = 2
	#Range: 1 ~ 3
	renderColumn = 1

#Chance to gather extra skins from animals
[skinning]
	#Range: 1 ~ 2
	renderRow = 1
	#Range: 1 ~ 3
	renderColumn = 2

#Chance to drop extra meat from animals
[meatgathering]
	#Range: 1 ~ 2
	renderRow = 2
	#Range: 1 ~ 3
	renderColumn = 2

#Increase speed under water
[swimspeed]
	#Range: 1 ~ 2
	renderRow = 1
	#Range: 1 ~ 3
	renderColumn = 3

#Decrease total cooking time
[cookingspeed]
	#Range: 1 ~ 2
	renderRow = 2
	#Range: 1 ~ 3
	renderColumn = 3

#Increase stone mining speed
[stonecutting]
	#Range: 1 ~ 2
	renderRow = 2
	#Range: 1 ~ 3
	renderColumn = 1

#Chance to increase yield from ores
[prospecting]
	#Range: 1 ~ 2
	renderRow = 1
	#Range: 1 ~ 3
	renderColumn = 2

#Increase wood chopping speed
[woodcutting]
	#Range: 1 ~ 2
	renderRow = 1
	#Range: 1 ~ 3
	renderColumn = 1

#Random chance to find treasure while digging
[treasurehunting]
	#Range: 1 ~ 2
	renderRow = 2
	#Range: 1 ~ 3
	renderColumn = 2

#Decrease fall damage taken
[softlanding]
	#Range: 1 ~ 2
	renderRow = 1
	#Range: 1 ~ 3
	renderColumn = 3

#Increase movement speed while sprinting
[sprintspeed]
	#Range: 1 ~ 2
	renderRow = 2
	#Range: 1 ~ 3
	renderColumn = 3

