<recipetype:create:sandpaper_polishing>.addRecipe("cluster1", <item:minecraft:amethyst_shard>*3, <item:quark:red_corundum_cluster>, 200);
<recipetype:create:sandpaper_polishing>.addRecipe("cluster2", <item:minecraft:amethyst_shard>*3, <item:quark:orange_corundum_cluster>, 200);
<recipetype:create:sandpaper_polishing>.addRecipe("cluster3", <item:minecraft:amethyst_shard>*3, <item:quark:yellow_corundum_cluster>, 200);
<recipetype:create:sandpaper_polishing>.addRecipe("cluster4", <item:minecraft:amethyst_shard>*3, <item:quark:green_corundum_cluster>, 200);
<recipetype:create:sandpaper_polishing>.addRecipe("cluster5", <item:minecraft:amethyst_shard>*3, <item:quark:blue_corundum_cluster>, 200);
<recipetype:create:sandpaper_polishing>.addRecipe("cluster6", <item:minecraft:amethyst_shard>*3, <item:quark:indigo_corundum_cluster>, 200);
<recipetype:create:sandpaper_polishing>.addRecipe("cluster7", <item:minecraft:amethyst_shard>*3, <item:quark:violet_corundum_cluster>, 200);
<recipetype:create:sandpaper_polishing>.addRecipe("cluster8", <item:minecraft:amethyst_shard>*3, <item:quark:white_corundum_cluster>, 200);
<recipetype:create:sandpaper_polishing>.addRecipe("cluster9", <item:minecraft:amethyst_shard>*3, <item:quark:black_corundum_cluster>, 200);